// <auto-generated />
namespace TMDT_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitData_07 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitData_07));
        
        string IMigrationMetadata.Id
        {
            get { return "202011201235419_InitData_07"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
